addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

before_script:
  - git config --global user.email "user@example.com"
  - git config --global user.name "Example User"

script:
  - cargo build --features mock
  - cargo test --features mock

notifications:
  email:
    on_success: never
