addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

before_script:
  - git config --global user.email "user@example.com"
  - git config --global user.name "Example User"
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH

script:
  - |
  if [[ "$TRAVIS_RUST_VERSION" == nightly* ]]; then
    travis-cargo test -- --no-default-features --features "unstable mock"
  else
    travis-cargo test -- --no-default-features --features "mock"
  fi

notifications:
  email:
    on_success: never
