addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

before_script:
  - git config --global user.email "user@example.com"
  - git config --global user.name "Example User"

language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

notifications:
  email:
    on_success: never
